---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: tyes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install dependecies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: "create a ~/web directory"
  file:
    path: ~/web
    state: directory

- name: "copy index test page from files/index.js to ~/web/index.js"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"


- name: "Start the weeb server using the command pm2 start ~/web/index.js -f"
  shell: |
    pm2 start ~/web/index.js -f